### ISSUE TITLE
Consider expanding the set of fee currencies used in e2e tests on alfajores

### ISSUE THREAD

**Issue by piersy** [celo-org/op-geth#259]
# Rationale

Its good to have more tests

# Implementation

Add them in the way that we already use USDC in the e2e tests on alfajores.

**Comment by Kourin1996** [comment]
@piersy 

How about setting the value of `FEE_CURRENCY` in `e2e_test/shared.sh` based on an environment variable, as shown in the following code?

```bash
case $NETWORK in
    # Get these values by querying the registry:
    # for contract in GoldToken FeeHandler FeeCurrencyDirectory
    #      cast call 0x000000000000000000000000000000000000ce10 "getAddressForStringOrDie(string calldata identifier) returns (address)" $contract
    #  end
    mainnet)
      export ETH_RPC_URL=wss://forno.celo.org/ws
      export TOKEN_ADDR=0x471EcE3750Da237f93B8E339c536989b8978a438
      export FEE_HANDLER=0xcD437749E43A154C07F3553504c68fBfD56B8778
      export FEE_CURRENCY=0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73
      export FEE_CURRENCY_DIRECTORY_ADDR=0x15F344b9E6c3Cb6F0376A36A64928b13F62C6276
      echo "Using mainnet network"
        ;;
    alfajores)
      export ETH_RPC_URL=wss://alfajores-forno.celo-testnet.org/ws
      export TOKEN_ADDR=0xF194afDf50B03e69Bd7D057c1Aa9e10c9954E4C9
      export FEE_HANDLER=0xEAaFf71AB67B5d0eF34ba62Ea06Ac3d3E2dAAA38
      export FEE_CURRENCY_DIRECTORY_ADDR=0x9212Fb72ae65367A7c887eC4Ad9bE310BAC611BF
      echo "Using Alfajores network"
      
      case $CURRENCY in
        USDC)
          echo "Set USDC address to FEE_CURRENCY"
          export FEE_CURRENCY=0x4822e58de6f5e485eF90df51C41CE01721331dC0
          ;;
        cUSD)
          echo "Set cUSD address to FEE_CURRENCY"
          export FEE_CURRENCY=0x874069Fa1Eb16D44d622F2e0Ca25eeA172369bC1
          ;;
        cEUR)
          echo "Set cEUR address to FEE_CURRENCY"
          export FEE_CURRENCY=0x10c892A6EC43a53E45D0B916B4b7D383B1b78C0F
          ;;
        '')
          echo "Set cUSD address to FEE_CURRENCY"
          export FEE_CURRENCY=0x874069Fa1Eb16D44d622F2e0Ca25eeA172369bC1
          ;;
      esac
        ;;
    baklava)
      export ETH_RPC_URL=wss://baklava-forno.celo-testnet.org/ws
      export TOKEN_ADDR=0xdDc9bE57f553fe75752D61606B94CBD7e0264eF8
      export FEE_HANDLER=0xeed0A69c51079114C280f7b936C79e24bD94013e
      export FEE_CURRENCY_DIRECTORY_ADDR=0xD59E1599F45e42Eb356202B2C714D6C7b734C034
      echo "Using Baklava network"
        ;;
    '')
      export ETH_RPC_URL=http://127.0.0.1:8545
      export TOKEN_ADDR=0x471ece3750da237f93b8e339c536989b8978a438
      export FEE_HANDLER=0xcd437749e43a154c07f3553504c68fbfd56b8778
      export FEE_CURRENCY=0x000000000000000000000000000000000000ce16
      export FEE_CURRENCY2=0x000000000000000000000000000000000000ce17
      export FEE_CURRENCY_DIRECTORY_ADDR=0x15F344b9E6c3Cb6F0376A36A64928b13F62C6276
      echo "Using local network"
        ;;
esac
```

**Comment by Kourin1996** [comment]
@piersy I have one question. Does Baklava support fee currency? Now I get the following error when sending a tx with fee currency.

```
    1) send fee currency tx with explicit gas fields and check receipt


  0 passing (1s)
  1 failing

  1) viem send tx
       send fee currency tx with explicit gas fields and check receipt:
     ParseRpcError: Invalid JSON was received by the server. An error occurred on the server while parsing the JSON text.

URL: wss://baklava-forno.celo-testnet.org/ws
Request body: {"method":"eth_sendRawTransaction","params":["0x7bf87f82f3703b0185018ce556cd83013c689400000000000000000000000000000000deadbeef0280c094f9ece301247ad2ce21894941830a2470f4e774ca80a016fb82557599ffceabc6e2f80e6712a08277aabf9192342de9b03dfe660116fda02ab21fdee9fb68c812905a3b45f88e83dc8298a2795e49a19a9766bc77fb09e3"]}

Details: failed input validation
Version: 2.21.27
      at withRetry.delay.count.count (file:///Users/yoshiki/Projects/celo/op-geth/e2e_test/js-tests/node_modules/viem/_esm/utils/buildRequest.js:27:31)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async attemptRetry (file:///Users/yoshiki/Projects/celo/op-geth/e2e_test/js-tests/node_modules/viem/_esm/utils/promise/withRetry.js:12:30)
```

**Comment by palango** [comment]
Maybe we should focus on the new testnet for this issue now and not spend more time on the current testnets.

**Comment by palango** [comment]
Postpone to Celo Sepolia.
