### ISSUE TITLE
Fix gas estimation in viem test

### ISSUE THREAD

**Issue by karlb** [celo-org/op-geth#78]
When removing the [fixed gas value](https://github.com/celo-org/op-geth/blob/571f3689935720336148fd7017ffe0910f03a5c4/e2e_test/js-tests/test_viem_tx.mjs#L103) in a viem test, the test fails with

```
EstimateGasExecutionError: Invalid parameters were provided to the RPC method.
Double check you have provided the correct parameters.

URL: http://127.0.0.1:8545
Request body: {"method":"eth_estimateGas","params":[{"account":{"address":"0x42cf1bbc38BaAA3c4898ce8790e21eD2738c6A4a","type":"json-rpc"},"type":"0x2","from":"0x42cf1bbc38BaAA3c4898ce8790e21eD2738c6A4a","chainId":1337,"maxFeePerGas":"0xe99b06ef","maxPriorityFeePerGas":"0xb2d05e00","nonce":"0x2","to":"0x00000000000000000000000000000000DeaDBeef","value":"0x1"}]}
 
Estimate Gas Arguments:
  from:                  0x42cf1bbc38BaAA3c4898ce8790e21eD2738c6A4a
  to:                    0x00000000000000000000000000000000DeaDBeef
  value:                 0.000000000000000001 A-CELO
  maxFeePerGas:          3.919251183 gwei
  maxPriorityFeePerGas:  3 gwei
  nonce:                 2

Details: invalid argument 0: json: cannot unmarshal non-string into Go struct field TransactionArgs.chainId of type *hexutil.Big
Version: viem@2.9.6
      at getEstimateGasError (file:///Users/karl/op-geth-wt2/e2e_test/js-tests/node_modules/viem/_esm/utils/errors/getEstimateGasError.js:11:12)
      at estimateGas (file:///Users/karl/op-geth-wt2/e2e_test/js-tests/node_modules/viem/_esm/actions/public/estimateGas.js:68:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async prepareTransactionRequest (file:///Users/karl/op-geth-wt2/e2e_test/js-tests/node_modules/viem/_esm/actions/wallet/prepareTransactionRequest.js:121:23)
      at async Context.<anonymous> (file:///Users/karl/op-geth-wt2/e2e_test/js-tests/test_viem_tx.mjs:99:19)
```

Check if the error is caused by viem on by our current op-geth implementation. Fix it if it is our problem, create a viem bug if they don't call the gas estimation correctly.

**Comment by ezdac** [comment]
The issue here is on viem's side - the call to `eth_estimateGas` sent undesired parameters in the request body (`{"account":{"address":"0x42cf1bbc38BaAA3c4898ce8790e21eD2738c6A4a","type":"json-rpc"}`) because their `transactionRequest` formatter was not filtering out redundant arguments.

This has already been [reported](https://github.com/wevm/viem/issues/2055)  and [fixed](https://github.com/wevm/viem/pull/2063) upstream, but we haven't updated to the appropriate version (`2.9.9`) yet.
